### ISSUE TITLE
Chest set up as a honey pot will not open

### ISSUE THREAD

**Issue by siyukatu** [TerrorByteTW/Honeypot#120]
**Describe the bug**
Chest set up as a honey pot will not open
I set the config to allow it, but it does not respond.

**To Reproduce**
1. Create honeypot
2. Right click on chest

**Expected behavior**
Display chest inventory.

**Version Info (please complete the following information):**
 - Honeypot Version: 2.5.3
 - Java Version 1.19.3
 - MC Server Version 1.19.3
 - MC Server Type Paper

**Comment by TerrrorByte** [comment]
@siyukatu Can you send me the following info?
1) Your inventory filters in the config
2) The Honeypot Logs (If you enabled them). They should be in the Honeypot plugin folder. Thanks!

**Comment by TerrrorByte** [comment]
Also, what kind of Honeypot are you trying to create? Is it a custom one, or a default one (Warn, ban, kick, etc.?) Also, note that Ender Chests are automatically bypassed since inventory contents are unique and I assume that opening an Ender Chest isn't a bad thing.

**Comment by TerrrorByte** [comment]
While I'm waiting for you to get me that info, I did look into the code to check the logic behind the PlayerInteractEvent which handles inventories.

It will only trigger if [all of the following conditions are met (code here)](https://github.com/TerrorByteTW/Honeypot/blob/8ef7b7c3bd2bb9fab30dd69f758511a75525fcab/honeypot-core/src/main/java/org/reprogle/honeypot/events/PlayerInteractEventListener.java#L79):

- The player is targeting a block that is at least within 5 blocks of them
- The block is a container
- The player right clicked it

After those 3 conditions are met, it will then:
- Check filters to see if they're enabled
  - If enabled, if the block is **not** in the filter, it will open the inventory without triggering it
  - If disabled, it will continue logic
- Check if the block is not an ender chest and that it's a Honeypot
- It will call the HoneypotPrePlayerInteractEvent. Other plugins can listen to this event and subsequently cancel it. If cancelled, the inventory is opened without triggering the Honeypot
- Finally, it will check if the inventory actions are enabled and if the player does not have exempt permissions, `honeypot.*` permissions, or is an Op
- If the Honeypot is using a custom action, it has to exist otherwise it won't trigger and will log an error in console and the Honeypot logs

Only after all these things are met will the Honeypot open. Essentially, this means that you have to make sure that:
1. You are opening an inventory within range
2. You are opening an inventory that is listed within the filters, if enabled
3. You are not opening an enderchest
4. No other plugins are hooking into Honeypot
5. Inventory Actions are enabled
6. You are not an Op, do not have exempt permissions, and don't have `honeypot.*` perms. 

Hopefully that isn't too much info! All of that is necessary to ensure the Honeypots don't accidentally trigger and have the most customization possible, but can make it pretty complicated to debug.

**Comment by siyukatu** [comment]
Inventory within the configuration tried all patterns. We also recently made one discovery.
It is that if you are within one block of a chest, you can open the chest.
I have the OP and can open the chest, but when the player right clicks on the chest nothing happens.

This is not a ender chest.
It's a normal large chest.

**Comment by TerrrorByte** [comment]
Sorry for the delay, currently moving. Will investigate soon!

**Comment by TerrrorByte** [comment]
Alright, so after some digging around in the code, it appears what you're experiencing is intended behavior. A player should not be able to open an inventory if `enable-container-actions` is set to true in the config. If `enable-container-actions` is set to true and inventory filters are on, container actions will only run on inventories within the filter list. 

I'm unsure as to why you'd want players to be able to open inventories if you've enable container actions, but I can easily rewrite that portion of code to at least allow you the option to do so via a config setting. I've went ahead and done so, and am releasing 2.5.4 to add that capability :)
